"""Schéma initial d'un cabinet — PostgreSQL

Migration unique remplaçant les 24 migrations MySQL historiques (0001→0024).
Le squash est volontaire : l'historique MySQL portait 18 `ALTER … MODIFY COLUMN
ENUM` et un trigger `SIGNAL SQLSTATE`, deux constructions sans équivalent
PostgreSQL, et ses `downgrade()` étaient de toute façon irrécupérables (les
types ENUM n'y étaient jamais supprimés). Rejouer cet historique n'aurait eu
aucune valeur : seul l'état final compte.

Cette migration est jouée UNE FOIS PAR CABINET, dans son propre schéma :

    alembic -x schema=tenant_<uuid> upgrade head

Révision : 0001
Révision précédente : néant
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Les colonnes PII sont typées `EncryptedString` (Fernet/AES-256, clé dérivée par
# cabinet) : la migration doit donc connaître le type applicatif.
import app.core.crypto

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'notaire_principal', 'responsable_conformite', 'clercs', 'declarant_centif', 'autre_utilisateur', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_backup_codes', sa.Text(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dossiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('type_client', sa.Enum('PP', 'PM', 'Association', 'Indivision', name='type_client_enum'), nullable=False),
    sa.Column('type_operation', sa.Enum('vente_immobiliere', 'manipulation_fonds', 'constitution_societe', 'fiducicommis', 'succession', 'donation', 'autre', name='type_operation_enum'), nullable=False),
    sa.Column('type_operation_detail', sa.String(length=255), nullable=True),
    sa.Column('montant_transaction', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('montant_tranche', sa.Enum('moins_15m', 'plus_15m', name='montant_tranche_enum'), nullable=True),
    sa.Column('mode_paiement', sa.Enum('virement', 'cheque', 'especes', 'mix', 'paiement_tiers', 'autre', name='mode_paiement_enum'), nullable=True),
    sa.Column('surveillance_espece', sa.Boolean(), nullable=False),
    sa.Column('nb_parties', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('brouillon', 'en_analyse', 'vigilance_renforcee', 'valide', 'bloque', 'traite', 'cloture', 'archive', name='statut_dossier_enum'), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('score_base', sa.Integer(), nullable=True),
    sa.Column('classification', sa.Enum('FAIBLE', 'MOYEN', 'ELEVE', name='classification_enum'), nullable=True),
    sa.Column('trigger_actif', sa.String(length=10), nullable=True),
    sa.Column('force_par_trigger', sa.Boolean(), nullable=False),
    sa.Column('vigilance_justification', sa.Text(), nullable=True),
    sa.Column('is_bloque', sa.Boolean(), nullable=False),
    sa.Column('archivage_date', sa.Date(), nullable=True),
    sa.Column('archivage_expiration', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('listes_sanctions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('type_liste', sa.Enum('GIABA', 'BCEAO', 'OFAC', 'UE_CSDNU', 'AUTRE', 'ONU_PROLIFERATION', 'OFAC_WMD', 'UE_PROLIFERATION', 'CENTIF_FP', name='type_liste_sanctions_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_entrees', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parametres_config',
    sa.Column('cle', sa.String(length=64), nullable=False),
    sa.Column('valeur', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('cle')
    )
    op.create_table('procedures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=True),
    sa.Column('type_alerte', sa.Enum('T1_PPE', 'T2_ESPECES', 'T3_SANCTIONS', 'T4_GAFI', 'T5_REFUS_DOC', 'T6_BE_NON_IDENTIFIABLE', 'INCOHERENCE_DOC', 'MONTAGE_COMPLEXE', 'SIGNALEMENT_INTERNE', 'DOSSIER_BLOQUE', 'DOS_ACCUSE_J15', 'PROLIFERATION_MATCH', 'RCCM_EXPIRE', 'SANCTIONS_PERIMEES', 'REVISION_ECHUE', 'AUTRE', name='type_alerte_enum'), nullable=False),
    sa.Column('signaleur_id', sa.String(length=36), nullable=True),
    sa.Column('niveau', sa.Enum('CRITIQUE', 'ELEVE', 'MOYEN', 'FAIBLE', 'INFO', name='niveau_alerte_enum'), nullable=False),
    sa.Column('statut', sa.Enum('ouverte', 'en_cours', 'traitee', 'ignoree', name='statut_alerte_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prise_en_charge_par', sa.String(length=36), nullable=True),
    sa.Column('prise_en_charge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('traite_par', sa.String(length=36), nullable=True),
    sa.Column('traite_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['prise_en_charge_par'], ['users.id'], ),
    sa.ForeignKeyConstraint(['signaleur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['traite_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autorisations_dirigeant',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('dirigeant_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.Enum('AUTORISE', 'REFUSE', name='decision_wrk09_enum'), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dirigeant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biens_immobiliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('nature', sa.String(length=255), nullable=True),
    sa.Column('adresse', sa.String(length=500), nullable=True),
    sa.Column('valeur', sa.Numeric(precision=15, scale=0), nullable=True),
    sa.Column('mode_financement', sa.Enum('virement_bancaire', 'cheque', 'especes', 'mix', 'paiement_tiers', 'autre', name='mode_financement_enum'), nullable=True),
    sa.Column('titres_fonciers', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentaires_internes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('declarations_suspicion',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('reference_interne', sa.String(length=50), nullable=False),
    sa.Column('statut', sa.Enum('brouillon', 'en_cours', 'soumis', 'accuse_recu', 'en_validation', 'validee_rc', 'transmise', 'classee', name='statut_dos_enum'), nullable=False),
    sa.Column('statut_operation', sa.Enum('executee', 'en_cours', 'tentee', name='statut_operation_dos_enum'), nullable=True),
    sa.Column('date_detection', sa.Date(), nullable=True),
    sa.Column('organisme_libelle', sa.String(length=255), nullable=True),
    sa.Column('organisme_adresse', sa.Text(), nullable=True),
    sa.Column('organisme_email', sa.String(length=255), nullable=True),
    sa.Column('organisme_telephone', sa.String(length=30), nullable=True),
    sa.Column('type_soupcon_bc', sa.Boolean(), nullable=False),
    sa.Column('type_soupcon_ft', sa.Boolean(), nullable=False),
    sa.Column('type_soupcon_prolif', sa.Boolean(), nullable=False),
    sa.Column('motifs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('statut_operations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detail_transactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('indices_blanchiment', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('identification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relations_affaires', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supports', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('autres_informations', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('decision', sa.Enum('transmettre', 'classer', name='decision_dos_enum'), nullable=True),
    sa.Column('motif_classement', sa.Text(), nullable=True),
    sa.Column('initie_par', sa.String(length=36), nullable=False),
    sa.Column('valide_par', sa.String(length=36), nullable=True),
    sa.Column('valide_par_rc', sa.String(length=36), nullable=True),
    sa.Column('valide_rc_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valide_par_dg', sa.String(length=36), nullable=True),
    sa.Column('valide_dg_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_transmission_centif', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transmis_par', sa.String(length=36), nullable=True),
    sa.Column('soumis_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accuse_recu_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accuse_recu_ref', sa.String(length=255), nullable=True),
    sa.Column('accuse_alerte_j15_envoyee', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['initie_par'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transmis_par'], ['users.id'], ),
    sa.ForeignKeyConstraint(['valide_par'], ['users.id'], ),
    sa.ForeignKeyConstraint(['valide_par_dg'], ['users.id'], ),
    sa.ForeignKeyConstraint(['valide_par_rc'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_interne')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('type_document', sa.String(length=80), nullable=False),
    sa.Column('nom_fichier', sa.String(length=500), nullable=False),
    sa.Column('minio_key', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('taille_octets', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dossiers_historique',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('statut_avant', sa.String(length=50), nullable=True),
    sa.Column('statut_apres', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrees_sanctions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('liste_id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=500), nullable=False),
    sa.Column('date_naissance', sa.String(length=40), nullable=True),
    sa.Column('nationalite', sa.String(length=120), nullable=True),
    sa.Column('lieu_naissance', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['liste_id'], ['listes_sanctions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations_risque',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('axe_type_client', sa.SmallInteger(), nullable=False),
    sa.Column('axe_pays_geographie', sa.SmallInteger(), nullable=False),
    sa.Column('axe_type_operation', sa.SmallInteger(), nullable=False),
    sa.Column('axe_montant', sa.SmallInteger(), nullable=False),
    sa.Column('axe_mode_paiement', sa.SmallInteger(), nullable=False),
    sa.Column('axe_complexite', sa.SmallInteger(), nullable=False),
    sa.Column('axe_ppe', sa.SmallInteger(), nullable=False),
    sa.Column('axe_coherence_doc', sa.SmallInteger(), nullable=False),
    sa.Column('axe_secteur', sa.SmallInteger(), nullable=False),
    sa.Column('axe_intermediaires', sa.SmallInteger(), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=False),
    sa.Column('classification', sa.Enum('FAIBLE', 'MOYEN', 'ELEVE', name='classification_enum'), nullable=False),
    sa.Column('trigger_principal', sa.String(length=10), nullable=True),
    sa.Column('triggers_actifs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('force_par_trigger', sa.Boolean(), nullable=False),
    sa.Column('sur_liste_sanctions', sa.Boolean(), nullable=False),
    sa.Column('pays_liste_noire_gafi', sa.Boolean(), nullable=False),
    sa.Column('pays_liste_grise_gafi', sa.Boolean(), nullable=False),
    sa.Column('refus_documents', sa.Boolean(), nullable=False),
    sa.Column('be_non_identifiable', sa.Boolean(), nullable=False),
    sa.Column('overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluated_by', sa.String(length=36), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['evaluated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id')
    )
    op.create_table('kyc_pm',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.Enum('initiale', 'actualisation', name='relation_type_pm_enum'), nullable=False),
    sa.Column('denomination_sociale', sa.String(length=255), nullable=False),
    sa.Column('nom_commercial', sa.String(length=255), nullable=True),
    sa.Column('forme_juridique', sa.String(length=50), nullable=True),
    sa.Column('pays_constitution', sa.String(length=100), nullable=True),
    sa.Column('nom_representant_legal', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('numero_rccm', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('date_emission_rccm', sa.Date(), nullable=True),
    sa.Column('date_expiration_rccm', sa.Date(), nullable=True),
    sa.Column('numero_contribuable', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('objet_social', sa.Text(), nullable=True),
    sa.Column('libelle_activite', sa.String(length=500), nullable=True),
    sa.Column('ca_annuel', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('effectif', sa.Integer(), nullable=True),
    sa.Column('pays_operations', sa.String(length=255), nullable=True),
    sa.Column('volume_transactions', sa.String(length=255), nullable=True),
    sa.Column('representant_statut_ppe', sa.Boolean(), nullable=False),
    sa.Column('adresse', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('telephone', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('whatsapp', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('email', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('mandataire', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ppe_detectee', sa.Boolean(), nullable=False),
    sa.Column('ppe_detail', sa.Text(), nullable=True),
    sa.Column('operations_cochees', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description_operation', sa.Text(), nullable=True),
    sa.Column('origine_fonds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('infos_pm', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('anciennete_pro', sa.Enum('moins_1_an', '1_a_10_ans', 'plus_10_ans', name='anciennete_pm_enum'), nullable=True),
    sa.Column('date_signature', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id')
    )
    op.create_table('kyc_pp',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.Enum('initiale', 'actualisation', name='relation_type_enum'), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('prenoms', sa.String(length=150), nullable=False),
    sa.Column('nom_jeune_fille', sa.String(length=150), nullable=True),
    sa.Column('nom_prenoms_pere', sa.String(length=255), nullable=True),
    sa.Column('nom_prenoms_mere', sa.String(length=255), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('lieu_naissance', sa.String(length=150), nullable=True),
    sa.Column('adresse_geo', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('adresse_postale', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('telephone', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('whatsapp', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('email', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('type_piece', sa.Enum('CNI', 'Passeport', 'Titre_sejour', 'Carte_consulaire', 'Autre', name='type_piece_pp_enum'), nullable=True),
    sa.Column('numero_piece', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('pays_emetteur_piece', sa.String(length=100), nullable=True),
    sa.Column('date_emission_piece', sa.Date(), nullable=True),
    sa.Column('date_expiration_piece', sa.Date(), nullable=True),
    sa.Column('mode_verification_piece', sa.Enum('original_vu', 'copie_certifiee', 'en_ligne', name='mode_verification_piece_enum'), nullable=True),
    sa.Column('numero_contribuable', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('sexe', sa.Enum('M', 'F', name='sexe_enum'), nullable=True),
    sa.Column('non_resident', sa.Boolean(), nullable=False),
    sa.Column('pays_residence', sa.String(length=100), nullable=True),
    sa.Column('ville_residence', sa.String(length=150), nullable=True),
    sa.Column('statut_matrimonial', sa.String(length=100), nullable=True),
    sa.Column('nationalite', sa.String(length=100), nullable=True),
    sa.Column('autres_nationalites', sa.String(length=255), nullable=True),
    sa.Column('profession', sa.String(length=255), nullable=True),
    sa.Column('profession_5_ans', sa.Text(), nullable=True),
    sa.Column('employeur', sa.String(length=255), nullable=True),
    sa.Column('secteur_activite', sa.String(length=255), nullable=True),
    sa.Column('retraite', sa.Boolean(), nullable=False),
    sa.Column('tranche_revenus', sa.Enum('moins_500k', '500k_2m', '2m_10m', 'plus_10m', name='tranche_revenus_enum'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('mandataire', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('est_ppe', sa.Boolean(), nullable=False),
    sa.Column('ppe_detail', sa.Text(), nullable=True),
    sa.Column('objet_relation', sa.Text(), nullable=True),
    sa.Column('operations_cochees', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description_operation', sa.Text(), nullable=True),
    sa.Column('origine_fonds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('anciennete_pro', sa.Enum('moins_1_an', '1_a_10_ans', 'plus_10_ans', name='anciennete_pp_enum'), nullable=True),
    sa.Column('date_signature', sa.Date(), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id')
    )
    op.create_table('procedure_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('procedure_id', sa.String(length=36), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('nom_fichier', sa.String(length=500), nullable=False),
    sa.Column('minio_key', sa.Text(), nullable=False),
    sa.Column('taille_octets', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedure_documents_procedure_id'), 'procedure_documents', ['procedure_id'], unique=False)
    op.create_table('revisions_kyc',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('classification_avant', sa.String(length=10), nullable=True),
    sa.Column('classification_apres', sa.String(length=10), nullable=True),
    sa.Column('score_avant', sa.Integer(), nullable=True),
    sa.Column('score_apres', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('planifiee', 'en_cours', 'completee', 'en_retard', 'vigilance_renforcee', 'bloquee', name='statut_revision_enum'), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=False),
    sa.Column('date_relance_1', sa.Date(), nullable=True),
    sa.Column('date_relance_2', sa.Date(), nullable=True),
    sa.Column('date_validation', sa.Date(), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('valide_par', sa.String(length=36), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('documents_mis_a_jour', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['valide_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dos_addendums',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dos_id', sa.String(length=36), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dos_id'], ['declarations_suspicion.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_actionnaires',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kyc_pm_id', sa.String(length=36), nullable=False),
    sa.Column('raison_sociale_nom', sa.String(length=255), nullable=False),
    sa.Column('type_personne', sa.Enum('PP', 'PM', name='type_personne_actionnaire_enum'), nullable=True),
    sa.Column('cni_passeport', sa.String(length=100), nullable=True),
    sa.Column('pourcentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('pays_residence', sa.String(length=100), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kyc_pm_id'], ['kyc_pm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_be',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kyc_pp_id', sa.String(length=36), nullable=True),
    sa.Column('kyc_pm_id', sa.String(length=36), nullable=True),
    sa.Column('raison_sociale_nom', sa.String(length=255), nullable=False),
    sa.Column('cni_passeport', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('pourcentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pourcentage_droits_vote', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('entite_intermediaire_nom', sa.String(length=255), nullable=True),
    sa.Column('entite_intermediaire_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pays_residence', sa.String(length=100), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('lieu_naissance', sa.String(length=150), nullable=True),
    sa.Column('nationalite', sa.String(length=100), nullable=True),
    sa.Column('lien_avec_client', sa.String(length=255), nullable=True),
    sa.Column('entreprise_cotee', sa.Boolean(), nullable=False),
    sa.Column('registre_be_demande', sa.Enum('oui', 'non', 'en_cours', name='registre_be_demande_enum'), nullable=True),
    sa.Column('registre_be_resultat', sa.Enum('conforme', 'divergence', 'non_trouve', name='registre_be_resultat_enum'), nullable=True),
    sa.Column('registre_be_note', sa.Text(), nullable=True),
    sa.Column('filtrage_sfc_resultat', sa.Enum('aucune', 'faux_positif', 'correspondance', name='filtrage_sfc_resultat_enum'), nullable=True),
    sa.Column('filtrage_sfc_listes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filtrage_sfc_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filtrage_sfc_justification', sa.Text(), nullable=True),
    sa.Column('statut_validation', sa.Enum('en_attente', 'valide', 'rejete', name='statut_validation_be_enum'), nullable=False),
    sa.Column('commentaire_validation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kyc_pm_id'], ['kyc_pm.id'], ),
    sa.ForeignKeyConstraint(['kyc_pp_id'], ['kyc_pp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_ppe',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kyc_pp_id', sa.String(length=36), nullable=True),
    sa.Column('kyc_pm_id', sa.String(length=36), nullable=True),
    sa.Column('statut_ppe', sa.Enum('Non_PPE', 'PPE_National', 'PPE_Etranger', 'Entourage_PPE', name='statut_ppe_enum'), nullable=False),
    sa.Column('fonctions', sa.Text(), nullable=True),
    sa.Column('pays_concerne', sa.String(length=100), nullable=True),
    sa.Column('verification_giaba', sa.Boolean(), nullable=False),
    sa.Column('verification_ofac', sa.Boolean(), nullable=False),
    sa.Column('verification_ue', sa.Boolean(), nullable=False),
    sa.Column('ras', sa.Boolean(), nullable=False),
    sa.Column('resultat_presse', sa.Enum('Negatif', 'Positif', 'Ambigu', name='resultat_presse_enum'), nullable=True),
    sa.Column('details_presse', sa.Text(), nullable=True),
    sa.Column('niveau_exposition', sa.Enum('Faible', 'Moyen', 'Eleve', name='niveau_exposition_ppe_enum'), nullable=True),
    sa.Column('mesures_proposees', sa.Text(), nullable=True),
    sa.Column('statut_validation', sa.Enum('en_attente', 'valide', 'rejete', name='statut_validation_ppe_enum'), nullable=False),
    sa.Column('commentaire_validation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_pm_id'], ['kyc_pm.id'], ),
    sa.ForeignKeyConstraint(['kyc_pp_id'], ['kyc_pp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Art. 23 / Art. 197 : un dossier archivé ne peut pas être supprimé avant
    # 10 ans, et sa destruction est une infraction pénale. La règle est portée
    # par la base et non par l'applicatif : aucun rôle, aucun chemin de code,
    # aucun accès direct au SGBD ne peut la contourner.
    #
    # L'équivalent MySQL (`SIGNAL SQLSTATE '45000'` dans un corps BEGIN…END
    # inline) n'existe pas en PostgreSQL : il faut une fonction plpgsql
    # déclenchée par le trigger.
    op.execute("""
        CREATE OR REPLACE FUNCTION prevent_archive_delete() RETURNS trigger AS $$
        BEGIN
            IF OLD.statut = 'archive' THEN
                RAISE EXCEPTION
                    'Suppression impossible : dossier archive - conservation 10 ans (Art. 23)'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            RETURN OLD;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER prevent_archive_delete
        BEFORE DELETE ON dossiers
        FOR EACH ROW EXECUTE FUNCTION prevent_archive_delete();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER IF EXISTS prevent_archive_delete ON dossiers')
    op.execute('DROP FUNCTION IF EXISTS prevent_archive_delete()')
    op.drop_table('kyc_ppe')
    op.drop_table('kyc_be')
    op.drop_table('kyc_actionnaires')
    op.drop_table('dos_addendums')
    op.drop_table('revisions_kyc')
    op.drop_index(op.f('ix_procedure_documents_procedure_id'), table_name='procedure_documents')
    op.drop_table('procedure_documents')
    op.drop_table('kyc_pp')
    op.drop_table('kyc_pm')
    op.drop_table('evaluations_risque')
    op.drop_table('entrees_sanctions')
    op.drop_table('dossiers_historique')
    op.drop_table('documents')
    op.drop_table('declarations_suspicion')
    op.drop_table('commentaires_internes')
    op.drop_table('biens_immobiliers')
    op.drop_table('autorisations_dirigeant')
    op.drop_table('alertes')
    op.drop_table('procedures')
    op.drop_table('parametres_config')
    op.drop_table('listes_sanctions')
    op.drop_table('dossiers')
    op.drop_table('audit_logs')
    op.drop_table('users')
    # Contrairement à MySQL, les types ENUM ne sont pas supprimés avec leurs
    # colonnes : sans ces DROP, tout downgrade suivi d'un upgrade échouerait
    # sur « type ... already exists ».
    op.execute('DROP TYPE IF EXISTS anciennete_pm_enum')
    op.execute('DROP TYPE IF EXISTS anciennete_pp_enum')
    op.execute('DROP TYPE IF EXISTS classification_enum')
    op.execute('DROP TYPE IF EXISTS decision_dos_enum')
    op.execute('DROP TYPE IF EXISTS decision_wrk09_enum')
    op.execute('DROP TYPE IF EXISTS filtrage_sfc_resultat_enum')
    op.execute('DROP TYPE IF EXISTS mode_financement_enum')
    op.execute('DROP TYPE IF EXISTS mode_paiement_enum')
    op.execute('DROP TYPE IF EXISTS mode_verification_piece_enum')
    op.execute('DROP TYPE IF EXISTS montant_tranche_enum')
    op.execute('DROP TYPE IF EXISTS niveau_alerte_enum')
    op.execute('DROP TYPE IF EXISTS niveau_exposition_ppe_enum')
    op.execute('DROP TYPE IF EXISTS registre_be_demande_enum')
    op.execute('DROP TYPE IF EXISTS registre_be_resultat_enum')
    op.execute('DROP TYPE IF EXISTS relation_type_enum')
    op.execute('DROP TYPE IF EXISTS relation_type_pm_enum')
    op.execute('DROP TYPE IF EXISTS resultat_presse_enum')
    op.execute('DROP TYPE IF EXISTS sexe_enum')
    op.execute('DROP TYPE IF EXISTS statut_alerte_enum')
    op.execute('DROP TYPE IF EXISTS statut_dos_enum')
    op.execute('DROP TYPE IF EXISTS statut_dossier_enum')
    op.execute('DROP TYPE IF EXISTS statut_operation_dos_enum')
    op.execute('DROP TYPE IF EXISTS statut_ppe_enum')
    op.execute('DROP TYPE IF EXISTS statut_revision_enum')
    op.execute('DROP TYPE IF EXISTS statut_validation_be_enum')
    op.execute('DROP TYPE IF EXISTS statut_validation_ppe_enum')
    op.execute('DROP TYPE IF EXISTS tranche_revenus_enum')
    op.execute('DROP TYPE IF EXISTS type_alerte_enum')
    op.execute('DROP TYPE IF EXISTS type_client_enum')
    op.execute('DROP TYPE IF EXISTS type_liste_sanctions_enum')
    op.execute('DROP TYPE IF EXISTS type_operation_enum')
    op.execute('DROP TYPE IF EXISTS type_personne_actionnaire_enum')
    op.execute('DROP TYPE IF EXISTS type_piece_pp_enum')
    op.execute('DROP TYPE IF EXISTS user_role_enum')
    # ### end Alembic commands ###
