"""Annuaire multi-tenant — schéma `shared`

Crée les seules tables vivant hors des schémas cabinet : cabinets, aiguillage
email → cabinet, comptes d'exploitation, journal d'exploitation. Aucune donnée
métier LBC/FT n'y figure — c'est ce qui rend le Super-Admin structurellement
aveugle aux dossiers.

Jouée UNE SEULE FOIS par déploiement :

    alembic -c alembic_shared.ini upgrade head

Révision : 0001
Révision précédente : néant
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_admins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='shared'
    )
    op.create_table('tenant_audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('super_admin_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='shared'
    )
    op.create_index(op.f('ix_shared_tenant_audit_log_tenant_id'), 'tenant_audit_log', ['tenant_id'], unique=False, schema='shared')
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('nom_cabinet', sa.String(length=255), nullable=False),
    sa.Column('schema_name', sa.String(length=63), nullable=False),
    sa.Column('statut', sa.Enum('configuration', 'production', 'suspendu', 'archive', name='tenant_statut_enum', schema='shared'), nullable=False),
    sa.Column('key_salt', sa.String(length=64), nullable=False),
    sa.Column('storage_bucket', sa.String(length=63), nullable=False),
    sa.Column('numero_agrement', sa.String(length=64), nullable=True),
    sa.Column('pays', sa.String(length=2), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_telephone', sa.String(length=32), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('totp_required', sa.Boolean(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('motif_suspension', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_agrement'),
    sa.UniqueConstraint('schema_name'),
    sa.UniqueConstraint('slug'),
    schema='shared'
    )
    op.create_table('tenant_users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['shared.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email'),
    schema='shared'
    )
    op.create_index(op.f('ix_shared_tenant_users_tenant_id'), 'tenant_users', ['tenant_id'], unique=False, schema='shared')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_tenant_users_tenant_id'), table_name='tenant_users', schema='shared')
    op.drop_table('tenant_users', schema='shared')
    op.drop_table('tenants', schema='shared')
    op.drop_index(op.f('ix_shared_tenant_audit_log_tenant_id'), table_name='tenant_audit_log', schema='shared')
    op.drop_table('tenant_audit_log', schema='shared')
    op.drop_table('super_admins', schema='shared')
    # Le type ENUM n'est pas supprimé avec sa colonne (contrairement à MySQL) :
    # sans ce DROP, un downgrade suivi d'un upgrade échouerait.
    op.execute('DROP TYPE IF EXISTS shared.tenant_statut_enum')
    # ### end Alembic commands ###
