"""Logo du cabinet

Ajoute la référence à l'identité visuelle du cabinet dans l'annuaire. Le fichier
lui-même reste dans le bucket du cabinet (isolation de niveau 3) : seule sa clé
est portée ici, afin que la barre latérale puisse l'afficher sans ouvrir de
session métier.

Révision : 0002
Révision précédente : 0001
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('logo_key', sa.String(length=255), nullable=True), schema='shared')
    op.add_column('tenants', sa.Column('logo_content_type', sa.String(length=64), nullable=True), schema='shared')
    op.add_column('tenants', sa.Column('logo_updated_at', sa.DateTime(timezone=True), nullable=True), schema='shared')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'logo_updated_at', schema='shared')
    op.drop_column('tenants', 'logo_content_type', schema='shared')
    op.drop_column('tenants', 'logo_key', schema='shared')
    # ### end Alembic commands ###
